spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/spring_swagger_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
